#if 0
#elif defined(__arm64__) && __arm64__
// Generated by Apple Swift version 5.1 (swiftlang-1100.0.270.13 clang-1100.0.33.7)
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wgcc-compat"

#if !defined(__has_include)
# define __has_include(x) 0
#endif
#if !defined(__has_attribute)
# define __has_attribute(x) 0
#endif
#if !defined(__has_feature)
# define __has_feature(x) 0
#endif
#if !defined(__has_warning)
# define __has_warning(x) 0
#endif

#if __has_include(<swift/objc-prologue.h>)
# include <swift/objc-prologue.h>
#endif

#pragma clang diagnostic ignored "-Wauto-import"
#include <Foundation/Foundation.h>
#include <stdint.h>
#include <stddef.h>
#include <stdbool.h>

#if !defined(SWIFT_TYPEDEFS)
# define SWIFT_TYPEDEFS 1
# if __has_include(<uchar.h>)
#  include <uchar.h>
# elif !defined(__cplusplus)
typedef uint_least16_t char16_t;
typedef uint_least32_t char32_t;
# endif
typedef float swift_float2  __attribute__((__ext_vector_type__(2)));
typedef float swift_float3  __attribute__((__ext_vector_type__(3)));
typedef float swift_float4  __attribute__((__ext_vector_type__(4)));
typedef double swift_double2  __attribute__((__ext_vector_type__(2)));
typedef double swift_double3  __attribute__((__ext_vector_type__(3)));
typedef double swift_double4  __attribute__((__ext_vector_type__(4)));
typedef int swift_int2  __attribute__((__ext_vector_type__(2)));
typedef int swift_int3  __attribute__((__ext_vector_type__(3)));
typedef int swift_int4  __attribute__((__ext_vector_type__(4)));
typedef unsigned int swift_uint2  __attribute__((__ext_vector_type__(2)));
typedef unsigned int swift_uint3  __attribute__((__ext_vector_type__(3)));
typedef unsigned int swift_uint4  __attribute__((__ext_vector_type__(4)));
#endif

#if !defined(SWIFT_PASTE)
# define SWIFT_PASTE_HELPER(x, y) x##y
# define SWIFT_PASTE(x, y) SWIFT_PASTE_HELPER(x, y)
#endif
#if !defined(SWIFT_METATYPE)
# define SWIFT_METATYPE(X) Class
#endif
#if !defined(SWIFT_CLASS_PROPERTY)
# if __has_feature(objc_class_property)
#  define SWIFT_CLASS_PROPERTY(...) __VA_ARGS__
# else
#  define SWIFT_CLASS_PROPERTY(...)
# endif
#endif

#if __has_attribute(objc_runtime_name)
# define SWIFT_RUNTIME_NAME(X) __attribute__((objc_runtime_name(X)))
#else
# define SWIFT_RUNTIME_NAME(X)
#endif
#if __has_attribute(swift_name)
# define SWIFT_COMPILE_NAME(X) __attribute__((swift_name(X)))
#else
# define SWIFT_COMPILE_NAME(X)
#endif
#if __has_attribute(objc_method_family)
# define SWIFT_METHOD_FAMILY(X) __attribute__((objc_method_family(X)))
#else
# define SWIFT_METHOD_FAMILY(X)
#endif
#if __has_attribute(noescape)
# define SWIFT_NOESCAPE __attribute__((noescape))
#else
# define SWIFT_NOESCAPE
#endif
#if __has_attribute(warn_unused_result)
# define SWIFT_WARN_UNUSED_RESULT __attribute__((warn_unused_result))
#else
# define SWIFT_WARN_UNUSED_RESULT
#endif
#if __has_attribute(noreturn)
# define SWIFT_NORETURN __attribute__((noreturn))
#else
# define SWIFT_NORETURN
#endif
#if !defined(SWIFT_CLASS_EXTRA)
# define SWIFT_CLASS_EXTRA
#endif
#if !defined(SWIFT_PROTOCOL_EXTRA)
# define SWIFT_PROTOCOL_EXTRA
#endif
#if !defined(SWIFT_ENUM_EXTRA)
# define SWIFT_ENUM_EXTRA
#endif
#if !defined(SWIFT_CLASS)
# if __has_attribute(objc_subclassing_restricted)
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# else
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# endif
#endif
#if !defined(SWIFT_RESILIENT_CLASS)
# if __has_attribute(objc_class_stub)
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME) __attribute__((objc_class_stub))
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_class_stub)) SWIFT_CLASS_NAMED(SWIFT_NAME)
# else
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME)
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) SWIFT_CLASS_NAMED(SWIFT_NAME)
# endif
#endif

#if !defined(SWIFT_PROTOCOL)
# define SWIFT_PROTOCOL(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
# define SWIFT_PROTOCOL_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
#endif

#if !defined(SWIFT_EXTENSION)
# define SWIFT_EXTENSION(M) SWIFT_PASTE(M##_Swift_, __LINE__)
#endif

#if !defined(OBJC_DESIGNATED_INITIALIZER)
# if __has_attribute(objc_designated_initializer)
#  define OBJC_DESIGNATED_INITIALIZER __attribute__((objc_designated_initializer))
# else
#  define OBJC_DESIGNATED_INITIALIZER
# endif
#endif
#if !defined(SWIFT_ENUM_ATTR)
# if defined(__has_attribute) && __has_attribute(enum_extensibility)
#  define SWIFT_ENUM_ATTR(_extensibility) __attribute__((enum_extensibility(_extensibility)))
# else
#  define SWIFT_ENUM_ATTR(_extensibility)
# endif
#endif
#if !defined(SWIFT_ENUM)
# define SWIFT_ENUM(_type, _name, _extensibility) enum _name : _type _name; enum SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
# if __has_feature(generalized_swift_name)
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) enum _name : _type _name SWIFT_COMPILE_NAME(SWIFT_NAME); enum SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
# else
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) SWIFT_ENUM(_type, _name, _extensibility)
# endif
#endif
#if !defined(SWIFT_UNAVAILABLE)
# define SWIFT_UNAVAILABLE __attribute__((unavailable))
#endif
#if !defined(SWIFT_UNAVAILABLE_MSG)
# define SWIFT_UNAVAILABLE_MSG(msg) __attribute__((unavailable(msg)))
#endif
#if !defined(SWIFT_AVAILABILITY)
# define SWIFT_AVAILABILITY(plat, ...) __attribute__((availability(plat, __VA_ARGS__)))
#endif
#if !defined(SWIFT_WEAK_IMPORT)
# define SWIFT_WEAK_IMPORT __attribute__((weak_import))
#endif
#if !defined(SWIFT_DEPRECATED)
# define SWIFT_DEPRECATED __attribute__((deprecated))
#endif
#if !defined(SWIFT_DEPRECATED_MSG)
# define SWIFT_DEPRECATED_MSG(...) __attribute__((deprecated(__VA_ARGS__)))
#endif
#if __has_feature(attribute_diagnose_if_objc)
# define SWIFT_DEPRECATED_OBJC(Msg) __attribute__((diagnose_if(1, Msg, "warning")))
#else
# define SWIFT_DEPRECATED_OBJC(Msg) SWIFT_DEPRECATED_MSG(Msg)
#endif
#if !defined(IBSegueAction)
# define IBSegueAction
#endif
#if __has_feature(modules)
#if __has_warning("-Watimport-in-framework-header")
#pragma clang diagnostic ignored "-Watimport-in-framework-header"
#endif
@import Dispatch;
@import Foundation;
@import ObjectiveC;
@import PushKit;
@import UIKit;
#endif

#pragma clang diagnostic ignored "-Wproperty-attribute-mismatch"
#pragma clang diagnostic ignored "-Wduplicate-method-arg"
#if __has_warning("-Wpragma-clang-attribute")
# pragma clang diagnostic ignored "-Wpragma-clang-attribute"
#endif
#pragma clang diagnostic ignored "-Wunknown-pragmas"
#pragma clang diagnostic ignored "-Wnullability"

#if __has_attribute(external_source_symbol)
# pragma push_macro("any")
# undef any
# pragma clang attribute push(__attribute__((external_source_symbol(language="Swift", defined_in="SendBirdCalls",generated_declaration))), apply_to=any(function,enum,objc_interface,objc_category,objc_protocol))
# pragma pop_macro("any")
#endif


SWIFT_CLASS_NAMED("AuthenticateParams")
@interface SBCAuthenticateParams : NSObject
@property (nonatomic, copy) NSString * _Nonnull userId;
@property (nonatomic, copy) NSString * _Nullable accessToken;
@property (nonatomic, readonly, copy) NSData * _Nullable pushToken;
@property (nonatomic, readonly) BOOL unique;
- (nonnull instancetype)initWithUserId:(NSString * _Nonnull)userId accessToken:(NSString * _Nullable)accessToken pushToken:(NSData * _Nullable)pushToken unique:(BOOL)unique OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithUserId:(NSString * _Nonnull)userId accessToken:(NSString * _Nullable)accessToken;
- (nonnull instancetype)initWithUserId:(NSString * _Nonnull)userId pushToken:(NSData * _Nullable)pushToken unique:(BOOL)unique;
- (void)setPushWithToken:(NSData * _Nullable)token withUniqueness:(BOOL)unique;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


///
SWIFT_CLASS_NAMED("CallOptions")
@interface SBCCallOptions : NSObject
/// If <code>false</code>, the call is for audio only.
@property (nonatomic) BOOL isVideoCall;
/// Gets value from <code>CallConstraints</code> and sets <code>CallConstraints.audio</code> when it has been changed.
@property (nonatomic) BOOL isAudioEnabled;
/// \param isVideoCall <code>Bool</code> object assigned <code>false</code> as a default value.
///
/// \param isAudioEnabled <code>Bool</code> object assigned <code>true</code> as a default value.
///
- (nonnull instancetype)initWithIsVideoCall:(BOOL)isVideoCall isAudioEnabled:(BOOL)isAudioEnabled;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

@class SBCDirectCallUser;
enum SBCDirectCallUserRole : NSInteger;
enum SBCEndResult : NSInteger;
@protocol SBCDirectCallDelegate;

/// This class describes direct call.  It has an identifier as an unique key.
SWIFT_CLASS_NAMED("DirectCall")
@interface SBCDirectCall : NSObject
/// Call ID of the call. The value has been got from <code>UUID</code>.
@property (nonatomic, readonly, copy) NSString * _Nonnull callId;
/// The caller’s object.
/// note:
/// If you want to show caller’s name on the call screen, use <code>remoteUser</code> or <code>localUser</code> instead of <code>caller</code>
@property (nonatomic, readonly, strong) SBCDirectCallUser * _Nullable caller;
/// The callee’s object.
/// note:
/// If you want to show callee’s name on the call screen, use <code>remoteUser</code> or <code>localUser instead of </code>callee`
@property (nonatomic, readonly, strong) SBCDirectCallUser * _Nullable callee;
/// The remote user of the call.  If you’re a caller, the <code>remoteUser</code> is <code>callee</code> as its role status.
/// \code
/// guard let remoteUser = self.call.remoteUser else { return }
/// self.remoteUserIdLabel.text = remoteUser.userId
///
/// \endcode
@property (nonatomic, readonly, strong) SBCDirectCallUser * _Nullable remoteUser;
/// The local user of the call. It has same status of role as current user.
/// \code
/// guard let localUser = self.call.localUser else { return }
/// self.localUserIdLabel.text = localUser.userId
///
/// \endcode
@property (nonatomic, readonly, strong) SBCDirectCallUser * _Nullable localUser;
/// The role of the current user.  This property has <code>UserRole.none</code>as an initial value.
@property (nonatomic, readonly) enum SBCDirectCallUserRole myRole;
/// End Result of the ended call
@property (nonatomic, readonly) enum SBCEndResult endResult;
/// Boolean value of whether the call is ended
@property (nonatomic, readonly) BOOL isEnded;
/// The start time of call. Int64 of miliseconds.
/// important:
///
/// Returns 0 if the call hasn’t started.
@property (nonatomic, readonly) int64_t startedAt;
/// The ended time of call. Int64 of miliseconds.
/// important:
///
/// Returns 0 if the call hasn’t ended.
@property (nonatomic, readonly) int64_t endedAt;
/// The duration of the call. Int64 of miliseconds.
/// important:
///
/// Returns 0 if the call hasn’t started.
@property (nonatomic, readonly) int64_t duration;
/// The muted status of the remote user.
@property (nonatomic, readonly) BOOL isRemoteAudioEnabled;
/// The muted status of the local user.
@property (nonatomic, readonly) BOOL isLocalAudioEnabled;
/// Is the call Video Call.
@property (nonatomic, readonly) BOOL isVideoCall;
/// <code>DirectCallDelegate</code>
/// \code
/// call.delegate?.someMethod()
///
/// \endcode
@property (nonatomic, weak) id <SBCDirectCallDelegate> _Nullable delegate;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

/// User Role of Direct Call
/// <ul>
///   <li>
///     Cases:
///     <ul>
///       <li>
///         caller: The user made the call.
///       </li>
///       <li>
///         callee: Ther user received the call.
///       </li>
///     </ul>
///   </li>
/// </ul>
typedef SWIFT_ENUM_NAMED(NSInteger, SBCDirectCallUserRole, "UserRole", open) {
  SBCDirectCallUserRoleCaller = 0,
  SBCDirectCallUserRoleCallee = 1,
};


@interface SBCDirectCall (SWIFT_EXTENSION(SendBirdCalls))
/// The UUID form of callId. Useful when dealing with CallKit.
@property (nonatomic, readonly, copy) NSUUID * _Nullable callUUID;
@end




@interface SBCDirectCall (SWIFT_EXTENSION(SendBirdCalls))
/// Requests <code>ACCEPT</code> to <em>SendBird</em> server and sets up Turn credential. This method is called when the callee accepts incoming call.
/// <ul>
///   <li>
///     parameters:
///   </li>
///   <li>
///     callOptions: Set up the call that you’re receiving. Cannot be empty
///   </li>
/// </ul>
- (void)acceptWithCallOptions:(SBCCallOptions * _Nonnull)callOptions;
/// Requests <code>End</code> to <em>SendBird</em> server and sets up ended call’s information. This method is called when the callee ends / declines / cancels call.
- (void)end;
/// Mutes the audio of local user
- (void)muteMicrophone;
/// Unmute the audio of local user
- (void)unmuteMicrophone;
@end








/// You can implement and invoke specific methods for each state of call.
/// \code
/// override func viewDidLoad() {
///    // ...
///    call.delegate = self
/// }
///
/// // ...
///
/// \endcode
SWIFT_PROTOCOL_NAMED("DirectCallDelegate")
@protocol SBCDirectCallDelegate
@optional
/// Invoked when callee accepted, but WebRTC has not been connected yet.
- (void)didEstablish:(SBCDirectCall * _Nonnull)call;
@required
/// Invoked when WebRTC has been connected. The caller and callee can have conversation with.
/// \code
/// func didConnect(_ call: DirectCall) {
///    self.endButton.isEnabled = true
/// }
///
/// \endcode
- (void)didConnect:(SBCDirectCall * _Nonnull)call;
@optional
/// Invoked when remote audio has been changed.
/// \code
/// func didRemoteAudioSettingsChange(_ call: DirectCall) {
///    guard call.isRemoteAudioEnabled == false else { return }
///    self.remoteAudioStatusLabel.text = "Muted"
/// }
///
/// \endcode
- (void)didRemoteAudioSettingsChange:(SBCDirectCall * _Nonnull)call;
@required
/// Invoked when call has been ended.
/// \code
/// func didEnd(_ call: DirectCall) {
///    self.dismiss(animated: true, completion: nil)
/// }
///
/// \endcode
- (void)didEnd:(SBCDirectCall * _Nonnull)call;
@end


/// Direct Call Log
SWIFT_CLASS_NAMED("DirectCallLog")
@interface SBCDirectCallLog : NSObject
/// Call Id of the Call
@property (nonatomic, readonly, copy) NSString * _Nonnull callId;
/// The started time of the Call. Int64 of miliseconds.
@property (nonatomic, readonly) int64_t startedAt;
/// The ended time of the Call. Int64 of miliseconds.
@property (nonatomic, readonly) int64_t endedAt;
/// The duration of the Call. Int64 of miliseconds.
@property (nonatomic, readonly) int64_t duration;
/// DirectCallUser that ended the call.
@property (nonatomic, readonly, strong) SBCDirectCallUser * _Nullable endedBy;
/// The caller of the call.
@property (nonatomic, readonly, strong) SBCDirectCallUser * _Nullable caller;
/// The callee of the call.
@property (nonatomic, readonly, strong) SBCDirectCallUser * _Nullable callee;
/// The end result of the call.
@property (nonatomic, readonly) enum SBCEndResult endResult;
/// The role of the current user in the call.
@property (nonatomic, readonly) enum SBCDirectCallUserRole myRole;
@property (nonatomic, readonly) BOOL isVideoCall;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

enum UserRoleFilter : NSInteger;
@class NSArray;
@class SBCError;

/// Query to fetch DirectCallLogs
SWIFT_CLASS_NAMED("DirectCallLogListQuery")
@interface SBCDirectCallLogListQuery : NSObject
@property (nonatomic, readonly) BOOL isLoading;
@property (nonatomic, readonly) BOOL hasNext;
@property (nonatomic, readonly) enum UserRoleFilter myRole;
@property (nonatomic, readonly, strong) NSArray * _Nonnull endResultsArray;
@property (nonatomic, readonly) int32_t limit;
- (void)nextWithCompletionHandler:(void (^ _Nonnull)(NSArray<SBCDirectCallLog *> * _Nullable, SBCError * _Nullable))completionHandler;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

typedef SWIFT_ENUM(NSInteger, UserRoleFilter, open) {
  UserRoleFilterCaller = 0,
  UserRoleFilterCallee = 1,
  UserRoleFilterAll = 2,
};


SWIFT_CLASS_NAMED("Params")
@interface SBCDirectCallLogListQueryParams : NSObject
@property (nonatomic) enum UserRoleFilter myRole;
@property (nonatomic, readonly, strong) NSArray * _Nonnull endResultsArray;
- (void)addWithEndResult:(enum SBCEndResult)endResult;
- (void)removeWithEndResult:(enum SBCEndResult)endResult;
@property (nonatomic) int32_t limit;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


/// This class represents a caller and a callee
SWIFT_CLASS_NAMED("User")
@interface SBCUser : NSObject
/// The user ID of the call user.
@property (nonatomic, readonly, copy) NSString * _Nonnull userId;
/// (Optional value) The nickname of the call user.
@property (nonatomic, readonly, copy) NSString * _Nullable nickname;
/// (Optional value) The profile image URL of the call user.
@property (nonatomic, readonly, copy) NSString * _Nullable profileURL;
/// (Optional value) The metadata.
@property (nonatomic, readonly, copy) NSDictionary<NSString *, NSString *> * _Nullable metadata;
/// The status of acitivity.  If it is <code>false</code>, the user is offline.
/// <ul>
///   <li>
///     Default: <code>false</code>
///   </li>
/// </ul>
@property (nonatomic, readonly) BOOL isActive;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


SWIFT_CLASS_NAMED("DirectCallUser")
@interface SBCDirectCallUser : SBCUser
/// Shows whether the user is caller or callee.
@property (nonatomic, readonly) enum SBCDirectCallUserRole role;
@end

typedef SWIFT_ENUM_NAMED(NSInteger, SBCEndResult, "EndResult", open) {
  SBCEndResultNone = 0,
  SBCEndResultCompleted = 1,
  SBCEndResultCanceled = 2,
  SBCEndResultDeclined = 3,
  SBCEndResultOtherDeviceAccepted = 4,
  SBCEndResultTimedOut = 5,
  SBCEndResultConnectionLost = 6,
  SBCEndResultNoAnswer = 7,
  SBCEndResultDialFailed = 8,
  SBCEndResultAcceptFailed = 9,
  SBCEndResultUnknown = 10,
};



@class NSCoder;

SWIFT_CLASS("_TtC13SendBirdCalls8SBCError")
@interface SBCError : NSError
- (nonnull instancetype)initWithDomain:(NSString * _Nonnull)domain code:(NSInteger)code userInfo:(NSDictionary<NSString *, id> * _Nullable)userInfo SWIFT_UNAVAILABLE;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
@end

typedef SWIFT_ENUM_NAMED(NSInteger, SBCErrorCode, "ErrorCode", open) {
  SBCErrorCodeDialCanceled = 1800100,
  SBCErrorCodeDialMyself = 1800101,
  SBCErrorCodeHttpRequestFailed = 1800200,
  SBCErrorCodeWsResponseTimeout = 1800203,
  SBCErrorCodeWsConnectionLost = 1800204,
  SBCErrorCodeInvalidResponse = 1800205,
  SBCErrorCodeQueryInProgress = 1800206,
  SBCErrorCodeInternalServer = 1800207,
  SBCErrorCodeMalformedData = 1800208,
  SBCErrorCodeInvalidParameter = 1800300,
  SBCErrorCodeInvalidParameterType = 1800301,
  SBCErrorCodeNotInitializedSendBirdCall = 1800302,
  SBCErrorCodeNotAuthenticated = 1800303,
};


SWIFT_PROTOCOL("_TtP13SendBirdCalls14SBCLogReceiver_")
@protocol SBCLogReceiver
/// Shows up log with message. You have to implement this method to visualize logs in your app.
/// \code
/// var logs: [String] = []
///
/// func log(message: String) {
///    self.logs.append(message)
///    self.updateLogsView()
/// }
///
/// func updateLogsView() {
///    // ...
/// }
///
/// \endcode
- (void)logMessage:(NSString * _Nonnull)message;
@end


SWIFT_CLASS("_TtC13SendBirdCalls9SBCLogger")
@interface SBCLogger : NSObject
/// Adds receiver to receive logs from SendBirdCall Logger
/// \code
/// override func viewDidLoad() {
///    // ...
///    
///    SBCLogger.add(receiver: self)
/// }
///
/// \endcode\param receiver The object inheritted<code>SBCLogReceiver</code> to receive logs
///
+ (void)addWithReceiver:(id <SBCLogReceiver> _Nonnull)receiver;
/// Removes receiver added before.
/// \code
/// SBCLogger.remove(receiver: self)
///
/// \endcode\param receiver The object inheritted<code>SBCLogReceiver</code>
///
+ (void)removeWithReceiver:(id <SBCLogReceiver> _Nonnull)receiver;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

@protocol SBCSendBirdCallDelegate;
@class PKPushRegistry;
@class PKPushPayload;

SWIFT_CLASS_NAMED("SendBirdCall")
@interface SBCSendBirdCall : NSObject
/// The app id of your SendBird app. This property must be configured prior to using <code>SendBirdCall</code> methods.
/// important:
/// If you change the app ID, a previous configured app ID will be removed and all call will be canceled.
/// \code
/// SendBirdCall.appId = "YOUR_APP_ID"
/// // If the app ID is different with configured app ID,
/// // the configured app ID will be removed
/// // and all calls will be canceled.
///
/// \endcode
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, copy) NSString * _Nullable appId;)
+ (NSString * _Nullable)appId SWIFT_WARN_UNUSED_RESULT;
+ (void)setAppId:(NSString * _Nullable)newValue;
/// Configures the appId of your SendBird App.
/// App ID <em>must</em> be configured prior to using any SendBirdCall functions
/// \code
/// SendBirdCall.configure(appId: "YOUR_APP_ID")
///
/// \endcode\param appId Your own app ID from your dashboard
///
///
/// returns:
/// (Discardable)<code>Bool</code> value. If the paramter has an empty string or equal previous app ID, it returns <code>false</code>.
/// If the method configures app ID successfully, it returns <code>true</code>.
+ (BOOL)configureWithAppId:(NSString * _Nonnull)appId;
/// SendBird SDK Version
/// \code
/// self.versionLabel.text = "SendBirdCalls v\(SendBirdCall.sdkVersion)"
///
/// // "SendBirdCalls v1.0.0"
///
/// \endcode
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull sdkVersion;)
+ (NSString * _Nonnull)sdkVersion SWIFT_WARN_UNUSED_RESULT;
/// Specifies the queue that you want to use for callbacks and delegate methods
/// \param queue DispatchQueue that will be used when calling callbacks and delegates internally
///
+ (void)executeOnQueue:(dispatch_queue_t _Nonnull)queue;
/// Adds delegates to SendBirdCall for Call status changes
/// \code
/// SendBirdCall.addDelegate(self, identifier: "IDENTIFIER")
///
/// \endcode\param delegate SendBirdCallDelegate that listens to SendBirdCall events
///
/// \param identifier Identifier for the specific delegate
///
+ (void)addDelegate:(id <SBCSendBirdCallDelegate> _Nonnull)delegate identifier:(NSString * _Nonnull)identifier;
/// Remove delegate for the given identifier.
/// \param identifier String identifier for the delegate. If SendBirdCall doesn’t have the given identifier, it will be ignored.
///
+ (void)removeDelegateWithIdentifier:(NSString * _Nonnull)identifier;
/// Removes all delegate for SendBirdCall events.
+ (void)removeAllDelegates;
/// Returns call for call ID.
/// \param forCallId Call ID.
///
///
/// returns:
///
/// <code>DirectCall</code> object with corresponding call ID. It can be <code>nil</code>.
+ (SBCDirectCall * _Nullable)getCallForCallId:(NSString * _Nonnull)callId SWIFT_WARN_UNUSED_RESULT;
/// Returns the currently authenticated user.
///
/// returns:
///
/// User that is currently authenticated. Returns nil if no user exists.
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, strong) SBCUser * _Nullable currentUser;)
+ (SBCUser * _Nullable)currentUser SWIFT_WARN_UNUSED_RESULT;
/// Authenticates user with user ID and Access Token that you generated at SendBird Dashboard.
/// \code
/// let params = AuthenticateParams(userId: userId, accessToken: accessToken)
///
/// SendBirdCall.authenticate(params: params) { user, error in
///     guard let user = user, error == nil else { return }
///     // Authenticated Successfully
/// }
///
/// \endcode\param params <code>AuthenticateParams</code> that contains User Id, Access Token, Push Token, and Unique
///
/// \param completionHandler The handler to call when the authenication is complete.
///
+ (void)authenticateWithParams:(SBCAuthenticateParams * _Nonnull)params completionHandler:(void (^ _Nonnull)(SBCUser * _Nullable, SBCError * _Nullable))completionHandler;
/// Deauthenticates current user and clears remaining processes.
/// \code
/// var myPushToken: Data?
///
/// // ...
///
/// SendBirdCall.deauthenticate(pushToken: myPushToken) { error in
///    guard error == nil else { return }
///    // ...
/// }
///
/// \endcode\param pushToken Data of Push Token. Nullable. Doesn’t remove push token if the token is <code>nil</code>
///
/// \param completionHandler Error Handler to be called after deauthenticate process is finished
///
+ (void)deauthenticateWithPushToken:(NSData * _Nullable)pushToken completionHandler:(void (^ _Nullable)(SBCError * _Nullable))completionHandler;
/// Makes a call to user(callee) directly. (1:1 Call)
/// \code
/// SendBirdCall.dial(to: "Swan") { call, error in
///    guard let call = call, error == nil else { return }
///    // ...
/// }
///
/// \endcode\param calleeId The callee’s user ID
///
/// \param callOptions It has <code>CallOptions()</code> as a default value. The default value will make audio call.
///
///
/// returns:
/// (Discardable) <code>DirectCall</code> object. If the method failed to make a call, it would return <code>nil</code>.
+ (SBCDirectCall * _Nullable)dialTo:(NSString * _Nonnull)calleeId callOptions:(SBCCallOptions * _Nonnull)callOptions completionHandler:(void (^ _Nonnull)(SBCDirectCall * _Nullable, SBCError * _Nullable))completionHandler;
/// Handles incoming VoIP push with SendBirdCalls payload.
/// \code
/// func pushRegistry(_ registry: PKPushRegistry, didReceiveIncomingPushWith payload: PKPushPayload, for type: PKPushType, completion: @escaping () -> Void) {
///    SendBirdCall.pushRegistry(registry, didReceiveIncomingPushWith: payload, for: type) { uuid in
///        guard let uuid = uuid else { return }
///        // CXProvider has to report incoming call with uuid
///     }
/// }
///
/// \endcode\param registry <code>PKPushRegistry</code> object same as  <code>PKPushRegistryDelegate</code> registry.
///
/// \param payload <code>PKPushPayload</code> in incoming VoIP push notification.
///
/// \param type <code>PKPushType</code> of push(<code>VoIP</code>)
///
/// \param completionHandler This closure is invoked with <code>UUID</code> from the payload.
///
+ (void)pushRegistry:(PKPushRegistry * _Nonnull)registry didReceiveIncomingPushWith:(PKPushPayload * _Nonnull)payload for:(PKPushType _Nonnull)type completionHandler:(void (^ _Nullable)(NSUUID * _Nullable))completionHandler;
/// Registers token from VoIP push credential to SendBird Server.
/// \code
/// // PKPushRegistryDelegate
///
/// func pushRegistry(_ registry: PKPushRegistry, didUpdate pushCredentials: PKPushCredentials, for type: PKPushType) {
///     SendBirdCall.register(pushToken: pushCredentials.token, unique: true) { error in
///         guard let error = error else { return }
///         // ...
///     }
/// }
///
/// \endcode\param pushToken <code>Data</code> object from <code>pushCredential.token</code>.  Refer to <code>PKPushRegistryDelegate</code>
///
/// \param unique If it is false, you can register more token for multi devices. It has <code>false</code> as a default value.
///
+ (void)registerWithPushToken:(NSData * _Nullable)pushToken unique:(BOOL)unique completionHandler:(void (^ _Nullable)(SBCError * _Nullable))completionHandler;
/// Unregisters a push token of specific device.
/// \code
/// var myPushToken: Data?
///
/// // ...
///
/// SendBirdCall.unregister(pushToken: myPushToken) { error in
///    guard error == nil else { return }
///    // Unregistered successfully
/// }
///
/// \endcode\param pushToken Optional Data for the push token that you want to unregister
///
/// \param completionHandler ErrorHandler that returns callback with error.
///
+ (void)unregisterWithPushToken:(NSData * _Nullable)pushToken completionHandler:(void (^ _Nullable)(SBCError * _Nullable))completionHandler;
/// Unregister all push token registered to the current user(multi device).
/// \param completionHandler ErrorHandler that returns callback with error
///
+ (void)unregisterAllPushTokensWithCompletionHandler:(void (^ _Nullable)(SBCError * _Nullable))completionHandler;
/// Creates a Direct Call Log LIst Query from given params
/// \param params DirectCallLogListQuery Params with options for creating query.
///
///
/// returns:
///
/// DirectCallLogListQuery: returns optional query object
+ (SBCDirectCallLogListQuery * _Nullable)createDirectCallLogListQueryWith:(SBCDirectCallLogListQueryParams * _Nonnull)params SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


@interface SBCSendBirdCall (SWIFT_EXTENSION(SendBirdCalls))
+ (SBCDirectCall * _Nullable)getCallForUUID:(NSUUID * _Nonnull)callUUID SWIFT_WARN_UNUSED_RESULT;
@end


/// Delegate for SendBirdCall
SWIFT_PROTOCOL_NAMED("SendBirdCallDelegate")
@protocol SBCSendBirdCallDelegate
/// Invoked when the current user received a incoming call.
/// \param call <code>DirectCall</code> object,
///
- (void)didEnterRinging:(SBCDirectCall * _Nonnull)call;
@end




#if __has_attribute(external_source_symbol)
# pragma clang attribute pop
#endif
#pragma clang diagnostic pop

#elif defined(__ARM_ARCH_7A__) && __ARM_ARCH_7A__
// Generated by Apple Swift version 5.1 (swiftlang-1100.0.270.13 clang-1100.0.33.7)
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wgcc-compat"

#if !defined(__has_include)
# define __has_include(x) 0
#endif
#if !defined(__has_attribute)
# define __has_attribute(x) 0
#endif
#if !defined(__has_feature)
# define __has_feature(x) 0
#endif
#if !defined(__has_warning)
# define __has_warning(x) 0
#endif

#if __has_include(<swift/objc-prologue.h>)
# include <swift/objc-prologue.h>
#endif

#pragma clang diagnostic ignored "-Wauto-import"
#include <Foundation/Foundation.h>
#include <stdint.h>
#include <stddef.h>
#include <stdbool.h>

#if !defined(SWIFT_TYPEDEFS)
# define SWIFT_TYPEDEFS 1
# if __has_include(<uchar.h>)
#  include <uchar.h>
# elif !defined(__cplusplus)
typedef uint_least16_t char16_t;
typedef uint_least32_t char32_t;
# endif
typedef float swift_float2  __attribute__((__ext_vector_type__(2)));
typedef float swift_float3  __attribute__((__ext_vector_type__(3)));
typedef float swift_float4  __attribute__((__ext_vector_type__(4)));
typedef double swift_double2  __attribute__((__ext_vector_type__(2)));
typedef double swift_double3  __attribute__((__ext_vector_type__(3)));
typedef double swift_double4  __attribute__((__ext_vector_type__(4)));
typedef int swift_int2  __attribute__((__ext_vector_type__(2)));
typedef int swift_int3  __attribute__((__ext_vector_type__(3)));
typedef int swift_int4  __attribute__((__ext_vector_type__(4)));
typedef unsigned int swift_uint2  __attribute__((__ext_vector_type__(2)));
typedef unsigned int swift_uint3  __attribute__((__ext_vector_type__(3)));
typedef unsigned int swift_uint4  __attribute__((__ext_vector_type__(4)));
#endif

#if !defined(SWIFT_PASTE)
# define SWIFT_PASTE_HELPER(x, y) x##y
# define SWIFT_PASTE(x, y) SWIFT_PASTE_HELPER(x, y)
#endif
#if !defined(SWIFT_METATYPE)
# define SWIFT_METATYPE(X) Class
#endif
#if !defined(SWIFT_CLASS_PROPERTY)
# if __has_feature(objc_class_property)
#  define SWIFT_CLASS_PROPERTY(...) __VA_ARGS__
# else
#  define SWIFT_CLASS_PROPERTY(...)
# endif
#endif

#if __has_attribute(objc_runtime_name)
# define SWIFT_RUNTIME_NAME(X) __attribute__((objc_runtime_name(X)))
#else
# define SWIFT_RUNTIME_NAME(X)
#endif
#if __has_attribute(swift_name)
# define SWIFT_COMPILE_NAME(X) __attribute__((swift_name(X)))
#else
# define SWIFT_COMPILE_NAME(X)
#endif
#if __has_attribute(objc_method_family)
# define SWIFT_METHOD_FAMILY(X) __attribute__((objc_method_family(X)))
#else
# define SWIFT_METHOD_FAMILY(X)
#endif
#if __has_attribute(noescape)
# define SWIFT_NOESCAPE __attribute__((noescape))
#else
# define SWIFT_NOESCAPE
#endif
#if __has_attribute(warn_unused_result)
# define SWIFT_WARN_UNUSED_RESULT __attribute__((warn_unused_result))
#else
# define SWIFT_WARN_UNUSED_RESULT
#endif
#if __has_attribute(noreturn)
# define SWIFT_NORETURN __attribute__((noreturn))
#else
# define SWIFT_NORETURN
#endif
#if !defined(SWIFT_CLASS_EXTRA)
# define SWIFT_CLASS_EXTRA
#endif
#if !defined(SWIFT_PROTOCOL_EXTRA)
# define SWIFT_PROTOCOL_EXTRA
#endif
#if !defined(SWIFT_ENUM_EXTRA)
# define SWIFT_ENUM_EXTRA
#endif
#if !defined(SWIFT_CLASS)
# if __has_attribute(objc_subclassing_restricted)
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# else
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# endif
#endif
#if !defined(SWIFT_RESILIENT_CLASS)
# if __has_attribute(objc_class_stub)
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME) __attribute__((objc_class_stub))
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_class_stub)) SWIFT_CLASS_NAMED(SWIFT_NAME)
# else
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME)
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) SWIFT_CLASS_NAMED(SWIFT_NAME)
# endif
#endif

#if !defined(SWIFT_PROTOCOL)
# define SWIFT_PROTOCOL(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
# define SWIFT_PROTOCOL_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
#endif

#if !defined(SWIFT_EXTENSION)
# define SWIFT_EXTENSION(M) SWIFT_PASTE(M##_Swift_, __LINE__)
#endif

#if !defined(OBJC_DESIGNATED_INITIALIZER)
# if __has_attribute(objc_designated_initializer)
#  define OBJC_DESIGNATED_INITIALIZER __attribute__((objc_designated_initializer))
# else
#  define OBJC_DESIGNATED_INITIALIZER
# endif
#endif
#if !defined(SWIFT_ENUM_ATTR)
# if defined(__has_attribute) && __has_attribute(enum_extensibility)
#  define SWIFT_ENUM_ATTR(_extensibility) __attribute__((enum_extensibility(_extensibility)))
# else
#  define SWIFT_ENUM_ATTR(_extensibility)
# endif
#endif
#if !defined(SWIFT_ENUM)
# define SWIFT_ENUM(_type, _name, _extensibility) enum _name : _type _name; enum SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
# if __has_feature(generalized_swift_name)
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) enum _name : _type _name SWIFT_COMPILE_NAME(SWIFT_NAME); enum SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
# else
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) SWIFT_ENUM(_type, _name, _extensibility)
# endif
#endif
#if !defined(SWIFT_UNAVAILABLE)
# define SWIFT_UNAVAILABLE __attribute__((unavailable))
#endif
#if !defined(SWIFT_UNAVAILABLE_MSG)
# define SWIFT_UNAVAILABLE_MSG(msg) __attribute__((unavailable(msg)))
#endif
#if !defined(SWIFT_AVAILABILITY)
# define SWIFT_AVAILABILITY(plat, ...) __attribute__((availability(plat, __VA_ARGS__)))
#endif
#if !defined(SWIFT_WEAK_IMPORT)
# define SWIFT_WEAK_IMPORT __attribute__((weak_import))
#endif
#if !defined(SWIFT_DEPRECATED)
# define SWIFT_DEPRECATED __attribute__((deprecated))
#endif
#if !defined(SWIFT_DEPRECATED_MSG)
# define SWIFT_DEPRECATED_MSG(...) __attribute__((deprecated(__VA_ARGS__)))
#endif
#if __has_feature(attribute_diagnose_if_objc)
# define SWIFT_DEPRECATED_OBJC(Msg) __attribute__((diagnose_if(1, Msg, "warning")))
#else
# define SWIFT_DEPRECATED_OBJC(Msg) SWIFT_DEPRECATED_MSG(Msg)
#endif
#if !defined(IBSegueAction)
# define IBSegueAction
#endif
#if __has_feature(modules)
#if __has_warning("-Watimport-in-framework-header")
#pragma clang diagnostic ignored "-Watimport-in-framework-header"
#endif
@import Dispatch;
@import Foundation;
@import ObjectiveC;
@import PushKit;
@import UIKit;
#endif

#pragma clang diagnostic ignored "-Wproperty-attribute-mismatch"
#pragma clang diagnostic ignored "-Wduplicate-method-arg"
#if __has_warning("-Wpragma-clang-attribute")
# pragma clang diagnostic ignored "-Wpragma-clang-attribute"
#endif
#pragma clang diagnostic ignored "-Wunknown-pragmas"
#pragma clang diagnostic ignored "-Wnullability"

#if __has_attribute(external_source_symbol)
# pragma push_macro("any")
# undef any
# pragma clang attribute push(__attribute__((external_source_symbol(language="Swift", defined_in="SendBirdCalls",generated_declaration))), apply_to=any(function,enum,objc_interface,objc_category,objc_protocol))
# pragma pop_macro("any")
#endif


SWIFT_CLASS_NAMED("AuthenticateParams")
@interface SBCAuthenticateParams : NSObject
@property (nonatomic, copy) NSString * _Nonnull userId;
@property (nonatomic, copy) NSString * _Nullable accessToken;
@property (nonatomic, readonly, copy) NSData * _Nullable pushToken;
@property (nonatomic, readonly) BOOL unique;
- (nonnull instancetype)initWithUserId:(NSString * _Nonnull)userId accessToken:(NSString * _Nullable)accessToken pushToken:(NSData * _Nullable)pushToken unique:(BOOL)unique OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithUserId:(NSString * _Nonnull)userId accessToken:(NSString * _Nullable)accessToken;
- (nonnull instancetype)initWithUserId:(NSString * _Nonnull)userId pushToken:(NSData * _Nullable)pushToken unique:(BOOL)unique;
- (void)setPushWithToken:(NSData * _Nullable)token withUniqueness:(BOOL)unique;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


///
SWIFT_CLASS_NAMED("CallOptions")
@interface SBCCallOptions : NSObject
/// If <code>false</code>, the call is for audio only.
@property (nonatomic) BOOL isVideoCall;
/// Gets value from <code>CallConstraints</code> and sets <code>CallConstraints.audio</code> when it has been changed.
@property (nonatomic) BOOL isAudioEnabled;
/// \param isVideoCall <code>Bool</code> object assigned <code>false</code> as a default value.
///
/// \param isAudioEnabled <code>Bool</code> object assigned <code>true</code> as a default value.
///
- (nonnull instancetype)initWithIsVideoCall:(BOOL)isVideoCall isAudioEnabled:(BOOL)isAudioEnabled;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

@class SBCDirectCallUser;
enum SBCDirectCallUserRole : NSInteger;
enum SBCEndResult : NSInteger;
@protocol SBCDirectCallDelegate;

/// This class describes direct call.  It has an identifier as an unique key.
SWIFT_CLASS_NAMED("DirectCall")
@interface SBCDirectCall : NSObject
/// Call ID of the call. The value has been got from <code>UUID</code>.
@property (nonatomic, readonly, copy) NSString * _Nonnull callId;
/// The caller’s object.
/// note:
/// If you want to show caller’s name on the call screen, use <code>remoteUser</code> or <code>localUser</code> instead of <code>caller</code>
@property (nonatomic, readonly, strong) SBCDirectCallUser * _Nullable caller;
/// The callee’s object.
/// note:
/// If you want to show callee’s name on the call screen, use <code>remoteUser</code> or <code>localUser instead of </code>callee`
@property (nonatomic, readonly, strong) SBCDirectCallUser * _Nullable callee;
/// The remote user of the call.  If you’re a caller, the <code>remoteUser</code> is <code>callee</code> as its role status.
/// \code
/// guard let remoteUser = self.call.remoteUser else { return }
/// self.remoteUserIdLabel.text = remoteUser.userId
///
/// \endcode
@property (nonatomic, readonly, strong) SBCDirectCallUser * _Nullable remoteUser;
/// The local user of the call. It has same status of role as current user.
/// \code
/// guard let localUser = self.call.localUser else { return }
/// self.localUserIdLabel.text = localUser.userId
///
/// \endcode
@property (nonatomic, readonly, strong) SBCDirectCallUser * _Nullable localUser;
/// The role of the current user.  This property has <code>UserRole.none</code>as an initial value.
@property (nonatomic, readonly) enum SBCDirectCallUserRole myRole;
/// End Result of the ended call
@property (nonatomic, readonly) enum SBCEndResult endResult;
/// Boolean value of whether the call is ended
@property (nonatomic, readonly) BOOL isEnded;
/// The start time of call. Int64 of miliseconds.
/// important:
///
/// Returns 0 if the call hasn’t started.
@property (nonatomic, readonly) int64_t startedAt;
/// The ended time of call. Int64 of miliseconds.
/// important:
///
/// Returns 0 if the call hasn’t ended.
@property (nonatomic, readonly) int64_t endedAt;
/// The duration of the call. Int64 of miliseconds.
/// important:
///
/// Returns 0 if the call hasn’t started.
@property (nonatomic, readonly) int64_t duration;
/// The muted status of the remote user.
@property (nonatomic, readonly) BOOL isRemoteAudioEnabled;
/// The muted status of the local user.
@property (nonatomic, readonly) BOOL isLocalAudioEnabled;
/// Is the call Video Call.
@property (nonatomic, readonly) BOOL isVideoCall;
/// <code>DirectCallDelegate</code>
/// \code
/// call.delegate?.someMethod()
///
/// \endcode
@property (nonatomic, weak) id <SBCDirectCallDelegate> _Nullable delegate;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

/// User Role of Direct Call
/// <ul>
///   <li>
///     Cases:
///     <ul>
///       <li>
///         caller: The user made the call.
///       </li>
///       <li>
///         callee: Ther user received the call.
///       </li>
///     </ul>
///   </li>
/// </ul>
typedef SWIFT_ENUM_NAMED(NSInteger, SBCDirectCallUserRole, "UserRole", open) {
  SBCDirectCallUserRoleCaller = 0,
  SBCDirectCallUserRoleCallee = 1,
};


@interface SBCDirectCall (SWIFT_EXTENSION(SendBirdCalls))
/// The UUID form of callId. Useful when dealing with CallKit.
@property (nonatomic, readonly, copy) NSUUID * _Nullable callUUID;
@end




@interface SBCDirectCall (SWIFT_EXTENSION(SendBirdCalls))
/// Requests <code>ACCEPT</code> to <em>SendBird</em> server and sets up Turn credential. This method is called when the callee accepts incoming call.
/// <ul>
///   <li>
///     parameters:
///   </li>
///   <li>
///     callOptions: Set up the call that you’re receiving. Cannot be empty
///   </li>
/// </ul>
- (void)acceptWithCallOptions:(SBCCallOptions * _Nonnull)callOptions;
/// Requests <code>End</code> to <em>SendBird</em> server and sets up ended call’s information. This method is called when the callee ends / declines / cancels call.
- (void)end;
/// Mutes the audio of local user
- (void)muteMicrophone;
/// Unmute the audio of local user
- (void)unmuteMicrophone;
@end








/// You can implement and invoke specific methods for each state of call.
/// \code
/// override func viewDidLoad() {
///    // ...
///    call.delegate = self
/// }
///
/// // ...
///
/// \endcode
SWIFT_PROTOCOL_NAMED("DirectCallDelegate")
@protocol SBCDirectCallDelegate
@optional
/// Invoked when callee accepted, but WebRTC has not been connected yet.
- (void)didEstablish:(SBCDirectCall * _Nonnull)call;
@required
/// Invoked when WebRTC has been connected. The caller and callee can have conversation with.
/// \code
/// func didConnect(_ call: DirectCall) {
///    self.endButton.isEnabled = true
/// }
///
/// \endcode
- (void)didConnect:(SBCDirectCall * _Nonnull)call;
@optional
/// Invoked when remote audio has been changed.
/// \code
/// func didRemoteAudioSettingsChange(_ call: DirectCall) {
///    guard call.isRemoteAudioEnabled == false else { return }
///    self.remoteAudioStatusLabel.text = "Muted"
/// }
///
/// \endcode
- (void)didRemoteAudioSettingsChange:(SBCDirectCall * _Nonnull)call;
@required
/// Invoked when call has been ended.
/// \code
/// func didEnd(_ call: DirectCall) {
///    self.dismiss(animated: true, completion: nil)
/// }
///
/// \endcode
- (void)didEnd:(SBCDirectCall * _Nonnull)call;
@end


/// Direct Call Log
SWIFT_CLASS_NAMED("DirectCallLog")
@interface SBCDirectCallLog : NSObject
/// Call Id of the Call
@property (nonatomic, readonly, copy) NSString * _Nonnull callId;
/// The started time of the Call. Int64 of miliseconds.
@property (nonatomic, readonly) int64_t startedAt;
/// The ended time of the Call. Int64 of miliseconds.
@property (nonatomic, readonly) int64_t endedAt;
/// The duration of the Call. Int64 of miliseconds.
@property (nonatomic, readonly) int64_t duration;
/// DirectCallUser that ended the call.
@property (nonatomic, readonly, strong) SBCDirectCallUser * _Nullable endedBy;
/// The caller of the call.
@property (nonatomic, readonly, strong) SBCDirectCallUser * _Nullable caller;
/// The callee of the call.
@property (nonatomic, readonly, strong) SBCDirectCallUser * _Nullable callee;
/// The end result of the call.
@property (nonatomic, readonly) enum SBCEndResult endResult;
/// The role of the current user in the call.
@property (nonatomic, readonly) enum SBCDirectCallUserRole myRole;
@property (nonatomic, readonly) BOOL isVideoCall;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

enum UserRoleFilter : NSInteger;
@class NSArray;
@class SBCError;

/// Query to fetch DirectCallLogs
SWIFT_CLASS_NAMED("DirectCallLogListQuery")
@interface SBCDirectCallLogListQuery : NSObject
@property (nonatomic, readonly) BOOL isLoading;
@property (nonatomic, readonly) BOOL hasNext;
@property (nonatomic, readonly) enum UserRoleFilter myRole;
@property (nonatomic, readonly, strong) NSArray * _Nonnull endResultsArray;
@property (nonatomic, readonly) int32_t limit;
- (void)nextWithCompletionHandler:(void (^ _Nonnull)(NSArray<SBCDirectCallLog *> * _Nullable, SBCError * _Nullable))completionHandler;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

typedef SWIFT_ENUM(NSInteger, UserRoleFilter, open) {
  UserRoleFilterCaller = 0,
  UserRoleFilterCallee = 1,
  UserRoleFilterAll = 2,
};


SWIFT_CLASS_NAMED("Params")
@interface SBCDirectCallLogListQueryParams : NSObject
@property (nonatomic) enum UserRoleFilter myRole;
@property (nonatomic, readonly, strong) NSArray * _Nonnull endResultsArray;
- (void)addWithEndResult:(enum SBCEndResult)endResult;
- (void)removeWithEndResult:(enum SBCEndResult)endResult;
@property (nonatomic) int32_t limit;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


/// This class represents a caller and a callee
SWIFT_CLASS_NAMED("User")
@interface SBCUser : NSObject
/// The user ID of the call user.
@property (nonatomic, readonly, copy) NSString * _Nonnull userId;
/// (Optional value) The nickname of the call user.
@property (nonatomic, readonly, copy) NSString * _Nullable nickname;
/// (Optional value) The profile image URL of the call user.
@property (nonatomic, readonly, copy) NSString * _Nullable profileURL;
/// (Optional value) The metadata.
@property (nonatomic, readonly, copy) NSDictionary<NSString *, NSString *> * _Nullable metadata;
/// The status of acitivity.  If it is <code>false</code>, the user is offline.
/// <ul>
///   <li>
///     Default: <code>false</code>
///   </li>
/// </ul>
@property (nonatomic, readonly) BOOL isActive;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


SWIFT_CLASS_NAMED("DirectCallUser")
@interface SBCDirectCallUser : SBCUser
/// Shows whether the user is caller or callee.
@property (nonatomic, readonly) enum SBCDirectCallUserRole role;
@end

typedef SWIFT_ENUM_NAMED(NSInteger, SBCEndResult, "EndResult", open) {
  SBCEndResultNone = 0,
  SBCEndResultCompleted = 1,
  SBCEndResultCanceled = 2,
  SBCEndResultDeclined = 3,
  SBCEndResultOtherDeviceAccepted = 4,
  SBCEndResultTimedOut = 5,
  SBCEndResultConnectionLost = 6,
  SBCEndResultNoAnswer = 7,
  SBCEndResultDialFailed = 8,
  SBCEndResultAcceptFailed = 9,
  SBCEndResultUnknown = 10,
};



@class NSCoder;

SWIFT_CLASS("_TtC13SendBirdCalls8SBCError")
@interface SBCError : NSError
- (nonnull instancetype)initWithDomain:(NSString * _Nonnull)domain code:(NSInteger)code userInfo:(NSDictionary<NSString *, id> * _Nullable)userInfo SWIFT_UNAVAILABLE;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
@end

typedef SWIFT_ENUM_NAMED(NSInteger, SBCErrorCode, "ErrorCode", open) {
  SBCErrorCodeDialCanceled = 1800100,
  SBCErrorCodeDialMyself = 1800101,
  SBCErrorCodeHttpRequestFailed = 1800200,
  SBCErrorCodeWsResponseTimeout = 1800203,
  SBCErrorCodeWsConnectionLost = 1800204,
  SBCErrorCodeInvalidResponse = 1800205,
  SBCErrorCodeQueryInProgress = 1800206,
  SBCErrorCodeInternalServer = 1800207,
  SBCErrorCodeMalformedData = 1800208,
  SBCErrorCodeInvalidParameter = 1800300,
  SBCErrorCodeInvalidParameterType = 1800301,
  SBCErrorCodeNotInitializedSendBirdCall = 1800302,
  SBCErrorCodeNotAuthenticated = 1800303,
};


SWIFT_PROTOCOL("_TtP13SendBirdCalls14SBCLogReceiver_")
@protocol SBCLogReceiver
/// Shows up log with message. You have to implement this method to visualize logs in your app.
/// \code
/// var logs: [String] = []
///
/// func log(message: String) {
///    self.logs.append(message)
///    self.updateLogsView()
/// }
///
/// func updateLogsView() {
///    // ...
/// }
///
/// \endcode
- (void)logMessage:(NSString * _Nonnull)message;
@end


SWIFT_CLASS("_TtC13SendBirdCalls9SBCLogger")
@interface SBCLogger : NSObject
/// Adds receiver to receive logs from SendBirdCall Logger
/// \code
/// override func viewDidLoad() {
///    // ...
///    
///    SBCLogger.add(receiver: self)
/// }
///
/// \endcode\param receiver The object inheritted<code>SBCLogReceiver</code> to receive logs
///
+ (void)addWithReceiver:(id <SBCLogReceiver> _Nonnull)receiver;
/// Removes receiver added before.
/// \code
/// SBCLogger.remove(receiver: self)
///
/// \endcode\param receiver The object inheritted<code>SBCLogReceiver</code>
///
+ (void)removeWithReceiver:(id <SBCLogReceiver> _Nonnull)receiver;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

@protocol SBCSendBirdCallDelegate;
@class PKPushRegistry;
@class PKPushPayload;

SWIFT_CLASS_NAMED("SendBirdCall")
@interface SBCSendBirdCall : NSObject
/// The app id of your SendBird app. This property must be configured prior to using <code>SendBirdCall</code> methods.
/// important:
/// If you change the app ID, a previous configured app ID will be removed and all call will be canceled.
/// \code
/// SendBirdCall.appId = "YOUR_APP_ID"
/// // If the app ID is different with configured app ID,
/// // the configured app ID will be removed
/// // and all calls will be canceled.
///
/// \endcode
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, copy) NSString * _Nullable appId;)
+ (NSString * _Nullable)appId SWIFT_WARN_UNUSED_RESULT;
+ (void)setAppId:(NSString * _Nullable)newValue;
/// Configures the appId of your SendBird App.
/// App ID <em>must</em> be configured prior to using any SendBirdCall functions
/// \code
/// SendBirdCall.configure(appId: "YOUR_APP_ID")
///
/// \endcode\param appId Your own app ID from your dashboard
///
///
/// returns:
/// (Discardable)<code>Bool</code> value. If the paramter has an empty string or equal previous app ID, it returns <code>false</code>.
/// If the method configures app ID successfully, it returns <code>true</code>.
+ (BOOL)configureWithAppId:(NSString * _Nonnull)appId;
/// SendBird SDK Version
/// \code
/// self.versionLabel.text = "SendBirdCalls v\(SendBirdCall.sdkVersion)"
///
/// // "SendBirdCalls v1.0.0"
///
/// \endcode
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull sdkVersion;)
+ (NSString * _Nonnull)sdkVersion SWIFT_WARN_UNUSED_RESULT;
/// Specifies the queue that you want to use for callbacks and delegate methods
/// \param queue DispatchQueue that will be used when calling callbacks and delegates internally
///
+ (void)executeOnQueue:(dispatch_queue_t _Nonnull)queue;
/// Adds delegates to SendBirdCall for Call status changes
/// \code
/// SendBirdCall.addDelegate(self, identifier: "IDENTIFIER")
///
/// \endcode\param delegate SendBirdCallDelegate that listens to SendBirdCall events
///
/// \param identifier Identifier for the specific delegate
///
+ (void)addDelegate:(id <SBCSendBirdCallDelegate> _Nonnull)delegate identifier:(NSString * _Nonnull)identifier;
/// Remove delegate for the given identifier.
/// \param identifier String identifier for the delegate. If SendBirdCall doesn’t have the given identifier, it will be ignored.
///
+ (void)removeDelegateWithIdentifier:(NSString * _Nonnull)identifier;
/// Removes all delegate for SendBirdCall events.
+ (void)removeAllDelegates;
/// Returns call for call ID.
/// \param forCallId Call ID.
///
///
/// returns:
///
/// <code>DirectCall</code> object with corresponding call ID. It can be <code>nil</code>.
+ (SBCDirectCall * _Nullable)getCallForCallId:(NSString * _Nonnull)callId SWIFT_WARN_UNUSED_RESULT;
/// Returns the currently authenticated user.
///
/// returns:
///
/// User that is currently authenticated. Returns nil if no user exists.
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, strong) SBCUser * _Nullable currentUser;)
+ (SBCUser * _Nullable)currentUser SWIFT_WARN_UNUSED_RESULT;
/// Authenticates user with user ID and Access Token that you generated at SendBird Dashboard.
/// \code
/// let params = AuthenticateParams(userId: userId, accessToken: accessToken)
///
/// SendBirdCall.authenticate(params: params) { user, error in
///     guard let user = user, error == nil else { return }
///     // Authenticated Successfully
/// }
///
/// \endcode\param params <code>AuthenticateParams</code> that contains User Id, Access Token, Push Token, and Unique
///
/// \param completionHandler The handler to call when the authenication is complete.
///
+ (void)authenticateWithParams:(SBCAuthenticateParams * _Nonnull)params completionHandler:(void (^ _Nonnull)(SBCUser * _Nullable, SBCError * _Nullable))completionHandler;
/// Deauthenticates current user and clears remaining processes.
/// \code
/// var myPushToken: Data?
///
/// // ...
///
/// SendBirdCall.deauthenticate(pushToken: myPushToken) { error in
///    guard error == nil else { return }
///    // ...
/// }
///
/// \endcode\param pushToken Data of Push Token. Nullable. Doesn’t remove push token if the token is <code>nil</code>
///
/// \param completionHandler Error Handler to be called after deauthenticate process is finished
///
+ (void)deauthenticateWithPushToken:(NSData * _Nullable)pushToken completionHandler:(void (^ _Nullable)(SBCError * _Nullable))completionHandler;
/// Makes a call to user(callee) directly. (1:1 Call)
/// \code
/// SendBirdCall.dial(to: "Swan") { call, error in
///    guard let call = call, error == nil else { return }
///    // ...
/// }
///
/// \endcode\param calleeId The callee’s user ID
///
/// \param callOptions It has <code>CallOptions()</code> as a default value. The default value will make audio call.
///
///
/// returns:
/// (Discardable) <code>DirectCall</code> object. If the method failed to make a call, it would return <code>nil</code>.
+ (SBCDirectCall * _Nullable)dialTo:(NSString * _Nonnull)calleeId callOptions:(SBCCallOptions * _Nonnull)callOptions completionHandler:(void (^ _Nonnull)(SBCDirectCall * _Nullable, SBCError * _Nullable))completionHandler;
/// Handles incoming VoIP push with SendBirdCalls payload.
/// \code
/// func pushRegistry(_ registry: PKPushRegistry, didReceiveIncomingPushWith payload: PKPushPayload, for type: PKPushType, completion: @escaping () -> Void) {
///    SendBirdCall.pushRegistry(registry, didReceiveIncomingPushWith: payload, for: type) { uuid in
///        guard let uuid = uuid else { return }
///        // CXProvider has to report incoming call with uuid
///     }
/// }
///
/// \endcode\param registry <code>PKPushRegistry</code> object same as  <code>PKPushRegistryDelegate</code> registry.
///
/// \param payload <code>PKPushPayload</code> in incoming VoIP push notification.
///
/// \param type <code>PKPushType</code> of push(<code>VoIP</code>)
///
/// \param completionHandler This closure is invoked with <code>UUID</code> from the payload.
///
+ (void)pushRegistry:(PKPushRegistry * _Nonnull)registry didReceiveIncomingPushWith:(PKPushPayload * _Nonnull)payload for:(PKPushType _Nonnull)type completionHandler:(void (^ _Nullable)(NSUUID * _Nullable))completionHandler;
/// Registers token from VoIP push credential to SendBird Server.
/// \code
/// // PKPushRegistryDelegate
///
/// func pushRegistry(_ registry: PKPushRegistry, didUpdate pushCredentials: PKPushCredentials, for type: PKPushType) {
///     SendBirdCall.register(pushToken: pushCredentials.token, unique: true) { error in
///         guard let error = error else { return }
///         // ...
///     }
/// }
///
/// \endcode\param pushToken <code>Data</code> object from <code>pushCredential.token</code>.  Refer to <code>PKPushRegistryDelegate</code>
///
/// \param unique If it is false, you can register more token for multi devices. It has <code>false</code> as a default value.
///
+ (void)registerWithPushToken:(NSData * _Nullable)pushToken unique:(BOOL)unique completionHandler:(void (^ _Nullable)(SBCError * _Nullable))completionHandler;
/// Unregisters a push token of specific device.
/// \code
/// var myPushToken: Data?
///
/// // ...
///
/// SendBirdCall.unregister(pushToken: myPushToken) { error in
///    guard error == nil else { return }
///    // Unregistered successfully
/// }
///
/// \endcode\param pushToken Optional Data for the push token that you want to unregister
///
/// \param completionHandler ErrorHandler that returns callback with error.
///
+ (void)unregisterWithPushToken:(NSData * _Nullable)pushToken completionHandler:(void (^ _Nullable)(SBCError * _Nullable))completionHandler;
/// Unregister all push token registered to the current user(multi device).
/// \param completionHandler ErrorHandler that returns callback with error
///
+ (void)unregisterAllPushTokensWithCompletionHandler:(void (^ _Nullable)(SBCError * _Nullable))completionHandler;
/// Creates a Direct Call Log LIst Query from given params
/// \param params DirectCallLogListQuery Params with options for creating query.
///
///
/// returns:
///
/// DirectCallLogListQuery: returns optional query object
+ (SBCDirectCallLogListQuery * _Nullable)createDirectCallLogListQueryWith:(SBCDirectCallLogListQueryParams * _Nonnull)params SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


@interface SBCSendBirdCall (SWIFT_EXTENSION(SendBirdCalls))
+ (SBCDirectCall * _Nullable)getCallForUUID:(NSUUID * _Nonnull)callUUID SWIFT_WARN_UNUSED_RESULT;
@end


/// Delegate for SendBirdCall
SWIFT_PROTOCOL_NAMED("SendBirdCallDelegate")
@protocol SBCSendBirdCallDelegate
/// Invoked when the current user received a incoming call.
/// \param call <code>DirectCall</code> object,
///
- (void)didEnterRinging:(SBCDirectCall * _Nonnull)call;
@end




#if __has_attribute(external_source_symbol)
# pragma clang attribute pop
#endif
#pragma clang diagnostic pop

#endif
